### ISSUE TITLE
Dead links in "Optional Features"

### ISSUE THREAD

**Issue by harudagondi** [rhaiscript/book#14]
In this [page](https://rhai.rs/book/start/features.html), there are a lot of dead links. Specifically, all links that should redirect to the book have `{{rootUrl}}` in them. Removing `/start/{{rootUrl}}` fixes the problem.

**Comment by schungx** [comment]
Hhhmmm... The Tera processor hasn't been run.  Probably a problem created since I updated `mdbook` version.

Thanks for the report.  I'll fix it.

**Comment by schungx** [comment]
It is fixed now.  Thanks for raising this.
