### ISSUE TITLE
One page is not rendered correctly

### ISSUE THREAD

**Issue by FlawlessDeveloper** [rhaiscript/book#2]
## The page ([here](https://rhai.rs/book/patterns/multi-threading.html)) is not rendered correctly.
See:
![image](https://user-images.githubusercontent.com/37778817/113505107-1ef74f80-953d-11eb-9bdf-f444377571aa.png)
![image](https://user-images.githubusercontent.com/37778817/113505122-2cacd500-953d-11eb-9b2d-09cac6480eda.png)

All scripts and stylesheets could not be found:
![image](https://user-images.githubusercontent.com/37778817/113505144-51a14800-953d-11eb-8e41-70e4878bd867.png)

**Comment by schungx** [comment]
Not sure why it happened.  The relative paths are screwed up for this file.

Thanks for catching this.  It is now fixed.
