### ISSUE TITLE
Document RawEngine packages

### ISSUE THREAD

**Issue by rm-dr** [rhaiscript/book#26]
I came across a problem today running the following with a raw engine:

```rust
let test = [1,2,3];
for s in test {
    print(s);
}
```
Which resulted in an error "`For loop expects iterable type`".
This was caused by my raw engine being loaded without `BasicArrayPackage`.

This should probably be documented in the "Raw Engine" section, since the error here gives no hint as to what is wrong. A list of the features each `Basic*Package` enables would be nice.

**Comment by schungx** [comment]
Actually you can load the iterator yourself... It is just one call to `set_iterable`...

**Comment by schungx** [comment]
But maybe a better idea is to move the iterators out of the packages into builtin.

**Comment by schungx** [comment]
I have decided to solve this by duplicating the iterator registrations into both the iterators package as well as the regular packages.
